fs_main_home:
    path:     /
    defaults: { _controller: FSMainBundle:Foot:index }
    
fs_main_matches:
    path:      /matches/{season}/{round}
    defaults:
        _controller: FSMainBundle:Foot:matches
    requirements:
        season: \d+
        round: \d+
        
fs_main_standing:
    path:      /standing/{season}
    defaults: { _controller: FSMainBundle:Foot:standing }
    requirements:
        season: \d+
        
fs_main_team:
    path:      /team/{id}
    defaults: { _controller: FSMainBundle:Foot:team }
    requirements:
        id: \d+
    
fs_main_topplayers:
    path:      /topplayers/
    defaults: { _controller: FSMainBundle:Foot:topplayers }
    
fs_main_favorites:
    path:      /favorites/
    defaults: { _controller: FSMainBundle:Foot:favorites }
    
